### ISSUE TITLE
Cityscapes Benchmark Scripts

### ISSUE THREAD

**Issue by shubham1810** [VICO-UoE/MTPSL#2]
Hi,

Thanks for sharing the amazing work! Is there any plan to release the scripts for Cityscapes or PASCAL benchamark to reproduce the results in the paper?

**Comment by WeihongLi-ac** [comment]
Hi,

We have uploaded the code for cityscapes. Thanks!

**Comment by HereNowL** [comment]
Could you share the code for PASCAL?

**Comment by HereNowL** [comment]
> Hi,
> 
> We have uploaded the code for cityscapes. Thanks!

Could you share the code for PASCAL?

**Comment by WeihongLi-ac** [comment]
Hi,

We have released the label splits of  PASCAL and we are using the implementation from https://github.com/SimonVandenhende/Multi-Task-Learning-PyTorch. Happy to help if you have further questions on implementation on PASCAL.

Best wishes,
WH

**Comment by HereNowL** [comment]
> Hi,
> 
> We have released the label splits of PASCAL and we are using the implementation from https://github.com/SimonVandenhende/Multi-Task-Learning-PyTorch. Happy to help if you have further questions on implementation on PASCAL.
> 
> Best wishes, WH

Hi,

Could you provide a brief explanation of how to use this label splits of PASCAL?
